# Site settings
title: Bradley Hawkins
email: hawbra56@gmail.com
description: "Designer, father, husband, cyclist."
baseurl: ""
url: "bradhdesign.com"
twitter_username: bradleyhawkins
dribbble_username: BradleyHawkins
github_username:  hawbra56

# Build settings
markdown: kramdown
permalink: pretty
