# Site settings
title: Bradley Hawkins
email: hawbra56@gmail.com
description: "The portfolio of Bradley Hawkins"
baseurl: ""
url: "http://bradhdesign.com"
twitter_username: bradleyhawkins
dribbble_username: BradleyHawkins
github_username:  hawbra56

# Build settings
markdown: kramdown
permalink: pretty
